routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('tinker', function () {
    return Auth::user();
});



Auth::routes();

Route::post('ideas/{idea}/comment', 'IdeasController@storeComment')->name('ideas.comment.store');

Route::post('ideas/{idea}/vote', 'IdeasController@storeVote')->name('ideas.vote.store');

Route::resources([
    'ideas' => 'IdeasController',
    'comments'=> 'CommentsController'
]);

Route::get('', 'HomeController@index')->name('home');

Route::get('users', 'UserController@index')->name('showUsers');

Route::get('guestIdea', 'GuestController@showGuest')->name('guest');

app/Idea.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Idea extends Model
{
    use Notifiable;

    protected $fillable = [
        'title', 'content', 'implement', 'aspect'
    ];

    public function votes()
    {
        return $this->hasMany(Vote::class);
    }

    public function getNumUpVotes()
    {
        return $this->votes()->whereUp(true)->count();//naathan?
    }

    public function getNumDownVotes()
    {
        return $this->votes()->whereUp(false)->count();
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Http/Controllers/IdeasController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Idea;
use App\Http\Controllers\Controller;
use App\User;
use App\Vote;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class IdeasController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $Ideas = Idea::all(); //$abc = Idea::findOrFail(0);
        return view('Ideas.index', compact('Ideas'));

    }

    public function store(Request $req)
    {
        $params = $req->only('title', 'content', 'aspect');
        $newIdea = Auth::user()->ideas()->create($params);

        return redirect()->route('ideas.show', $newIdea->id);
    }

    protected function create()
    {
        return view('Ideas/newIdea');
    }
//    public function show(Idea $idea)
//    {
//        $Idea = Idea::all();
//        return view('Idea.index', compact('idea'));
//    }
    public function show(Idea $idea )
    {
        $vote = $idea->votes()->whereUserId(Auth::id())->first();
        return view('Ideas.singleIdea', compact('idea', 'vote'));
    }


    public function edit($id)
    {
        //
    }


    public function update(Request $request, $id)
    {
        //
    }


    public function destroy(Idea $idea)
    {
        $idea->delete();

        return redirect()->route('ideas.index');

    }

    public function storeComment(Request $request, Idea $idea)
    {
        $idea->comments()->create([
            'content' => $request->input('content'),
            'user_id' => Auth::id(),

        ]);
        return redirect('/ideas/' . $idea->id);
    }
    public function storeVote(Request $request, Idea $idea)
    {
        // turn the vote into true or false
        $up = filter_var($request->input('up'), FILTER_VALIDATE_BOOLEAN);
        return $idea->votes()->create([
            'up' => $up,
            'user_id' => Auth::id()
        ]);
    }



}

resources/views/Ideas/guestIdea.blade.php
@extends('layouts.app')
<style>
    #bg {
        background-image: url("../backBulb.jpeg");
        height: 100%;

    }

    #backwhite{
        background-color: rgba(201,215,2, 0.7);
        color: #1b1e21;
        border-radius: 4px;
        box-shadow: 0px 0px 12px rgba(0,205,0,0.9);
    }
    .textarea {
        resize: vertical;
        height: 40px;
        min-height: 40px;
        max-height:100px;
        font-size: 20px !important;
    }
</style>
    <div id="bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <br><br><br>
                    <div class="card" id="backwhite">
                        <div class="card-header">Submit your idea !!!</div>

                        <div class="card-body">
                            <form action='#' method="post">
                                @csrf
                                <br>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Title</span>
                                    </div>
                                    <textarea class="form-control form-control-sm textarea" name="title" aria-label="With textarea" required autofocus></textarea>
                                </div>

                                <br>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Content</span>
                                    </div>
                                    <textarea class="form-control textarea" name="content" aria-label="With textarea" required autofocus></textarea>
                                </div>
                                <br>
                                <br>
                                <div class="input-group">
                                    <select class="custom-select" id="inputGroupSelect04" name="aspect" aria-label="aspect">
                                        <option selected>Aspect of business...</option>
                                        <option value="Planning">Planning</option>
                                        <option value="Management">Management</option>
                                        <option value="Health, Safety, and Environment">Health, Safety, and Environment</option>
                                        <option value="Principles of Technology">Principles of Technology</option>
                                        <option value="Labor Issues">Labor Issues</option>
                                        <option value="Personal Work Habits">Personal Work Habits</option>
                                        <option value="other">Other...</option>


                                    </select>
                                    <div class="input-group-append">

                                        <button class="btn btn-outline-secondary" type="Submit">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

resources/views/Ideas/index.blade.php
@extends('layouts.app')

@section('styles')
    <link href="{{ asset('css/cards.css') }}" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
    .bg {
        background-image: url("../svg/wall.jpg");
        background-size: cover;
    }
    </style>
@endsection


@section('content')
    <div class="bg">
    <div class="container">
    <h1 style="text-align: center;">All Ideas</h1>
    <div class="row">
  @foreach ($Ideas as $idea)

          <div class="col-md-6">
            <div class="jumbotron">
                <h1 class="display-4">{{ $idea->title }}</h1>
                <hr class="my-4">
                <p>{{ $idea->content }}</p>
                <a class="btn btn-primary btn-lg" href="/ideas/{{ $idea->id }}" role="button">See the Idea !</a>
            </div>
          </div>

 @endforeach
    </div>
@endsection


    </div>
    </div>

resources/views/Ideas/newIdea.blade.php
@extends('layouts.app')
<style>
    .bg {
        background-image: url("../svg/write.jpg");
        background-size: cover;

    }

    #backwhite{
        background-color: rgba(0, 100, 0, 0.75);
        color: #1b1e21;
        border-radius: 20px;
    }
    .textarea {
        resize: vertical;
        height: 40px;
        min-height: 40px;
        max-height:100px;
        font-size: 20px !important;
    }
</style>
@section('content')
    <div class="bg">
        <div class="container">
            <br>
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="card" id="backwhite">
                        <div class="card-header"><code style="color: #fec400">Submit your idea!</code></div>

                        <div class="card-body">
                            <form action='{{ route('ideas.store') }}' method="post">
                                @csrf
                                <br>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Title</span>
                                    </div>
                                    <textarea class="form-control form-control-sm textarea" name="title" aria-label="With textarea" required autofocus></textarea>
                                </div>

                                <br>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">Content</span>
                                    </div>
                                    <textarea class="form-control textarea" name="content" aria-label="With textarea" required autofocus></textarea>
                                </div>
                                <br>

                                <div class="input-group">
                                    <select class="custom-select" id="inputGroupSelect04" name="aspect" aria-label="aspect">
                                        <option selected>Aspect of business...</option>
                                        <option value="Construction">Construction</option>
                                        <option value="Management">Management</option>
                                        <option value="Health, Safety, and Environment">Health, Safety, and Environment</option>
                                        <option value="Technology">Technology</option>
                                        <option value="HR and Recruitment">HR and Recruitment</option>
                                        <option value="Office management">Office management</option>
                                        <option value="other">Other...</option>


                                    </select>
                                    <div class="input-group-append">

                                        <button class="btn btn-outline-secondary" type="Submit">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br>
    </div>
@endsection
@section('create')
@endsection

resources/views/Ideas/singleIdea.blade.php
@extends('layouts.app')

    <style>
        .bg {
            background-image: url("../backBulb.jpeg");
            background-repeat: no-repeat;
            background-size: cover;
        }

        .backwhite{
            background-color: rgba(255,255,255, 0.85);
            color: #1b1e21;
        }
        .comment {
            padding: 0 5px;
            border: 1px solid #000;
            border-radius: 5px;
            margin-bottom: 20px;
            box-shadow: 0px 0px 12px rgba(0,0,0,0.9);
        }
        .ideaBox {
            padding: 0 5px;
            border: 1px solid #000;
            border-radius: 5px;
            margin-bottom: 20px;
            box-shadow: 0px 0px 12px rgba(255,255,0,0.9);
        }
        .commentForm {
            border-radius: 2px;
            box-shadow: 0px 0px 12px rgba(0,0,0,0.9);
        }
        .boxx {
            border-radius: 150px;
            box-shadow: 0px 0px 12px rgba(0,0,0,0.9);
        }

    </style>
@section('content')

    <div class="bg">
        <div class="container">
            <br>
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <div class="backwhite ideaBox">
                            <h1 style="text-align: center">{{$idea->title}}</h1>
                            <hr>
                            <h2>{{$idea->content}}</h2>
                    </div>
                </div>
            </div>

            <div class="row justify-content-center"  style="font-family: Times; color: darkgreen;">
                <div class="card backwhite boxx ">

                        <h5>Created by:
                            <span class="badge badge-pill badge-dark">{{$idea->user->name}}</span>
                        </h5>

                </div>
            </div>
            <br>
            <div class="row justify-content-center" style="font-family: Times; color: darkgreen;">
                <div class="card backwhite boxx ">

                        <h5>Aspect of business:
                            <span class="badge badge-pill badge-dark"> {{$idea->aspect  }}</span>
                        </h5>

                </div>
            </div>
            <br>
            <div class="row justify-content-center">
                <form action="#" method="get" class="vote-widget" >
                    <button :disabled="vote" type="button" name="up" class="btn btn-success" @click="upvote()">
                        Upvote
                        <span class="badge badge-light">@{{ up }}</span>
                        <span class="sr-only">Upvote</span>
                    </button>

                    <button :disabled="vote" type="button" name="down" class="btn btn-secondary" @click="downvote()">
                        Downvote
                        <span class="badge badge-light">@{{ down }}</span>
                        <span class="sr-only">Downvote</span>
                    </button>
                    <p style="color: #040505" v-if="vote">You @{{ vote.up ? 'Up' : 'Down' }}voted this!</p>
                </form>
            </div>
            <br>
            <div align="center" style="font-family: Times; color: yellow;">
                <h1>Comments</h1>
            </div>

            @include('comments.index', ['comments' => $idea->comments])


            <div class="row justify-content-center ">
                <div class="card backwhite ">


                    <div class="card-body commentForm">

                        <form action='{{ route('ideas.comment.store', $idea->id) }}' method="post">


                            @csrf


                            <div class="input-group mb-3">
                                <input type="text" name="content" class="form-control" placeholder="Write a comment..." aria-label="Recipient's username" aria-describedby="button-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-secondary" type="submit" name="GO!" id="button-addon2">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            @if ($idea->user_id == Auth::id())
                <form action="{{route('ideas.destroy', $idea->id)}}" method="post">
                    @method('delete')
                    @csrf
                    <button class="btn btn-danger">Delete the Idea</button>
                </form>
            @endif
            <br><br><br><br><br><br><br><br><br>

        </div>
    </div>



@endsection

@section('js')
    <script>
        var voteUrl = '{{ route('ideas.vote.store', $idea->id) }}';
        var upVotes = {{ $idea->getNumUpVotes() }};
        var downVotes = {{ $idea->getNumDownVotes() }};
        var vote = {!! $vote ? $vote : 'null' !!};
        new Vue({
            el: '.vote-widget',
            data: {
                up: upVotes,
                down: downVotes,
                vote: vote
            },
            methods: {
                upvote: function () {
                    this.doVote(true);
                },
                downvote: function () {
                    this.doVote(false);
                },
                doVote: function (up) {
                    var that = this;
                    var params = {
                        up: up,
                        _token: '{{ csrf_token() }}'
                    };
                    $.post(voteUrl, params, function () {

                    }).fail(function () {
                        alert('failed!!');
                        that.vote = null;

                        if (up)
                            that.up--;
                        else
                            that.down--;
                    });
                    this.vote = {up: up};
                    if (up)
                        this.up++;
                    else
                        this.down++;
                }
            }
        });

    </script>
@endsection